cronjobs:
  - name: "Perform check of services and disks at boot"
    special_time: "reboot"
    job: "flock --verbose -n /tmp/boot-check.lock bash {{ code_scripts_path }}/boot-check.sh"
    user: "{{ ansible_user }}"
  - name: "Perform system checks (CPU, RAM, disks)"
    minute: "*/15"
    job: "flock --verbose -n /tmp/system-check.lock {{ ansible_python_interpreter }} {{ code_scripts_path }}/system_checks.py > /dev/null"
    user : "{{ ansible_user }}"
  - name: "Perform multiple file operations"
    minute: "0"
    hour: "3"
    job: "bash {{ code_scripts_path }}/file_operations.sh"
    user: "{{ ansible_user }}"
  - name: "Trigger Asset UPnP library re-scan to recognize possible new album art"
    minute: "0"
    hour: "5"
    day: "*/7"
    job: "bash {{ code_scripts_path }}/assetupnp_rescan.sh"
    user: "{{ ansible_user }}"
  - name: "Keep NAS upnp_1 HDD (WD Elements) alive (spinning)"
    minute: "*/5"
    job: "flock --verbose -n /tmp/keepalive-nas-1.lock bash -c 'dd if=/dev/disk/by-uuid/185d6a8e-e9ac-43f0-933a-54427109c397 of=/dev/null count=1 skip=$RANDOM > /dev/null 2>&1' > /dev/null"
    user: root
  - name: "Keep NAS upnp_2 HDD (WD Elements) alive (spinning)"
    minute: "*/5"
    job: "flock --verbose -n /tmp/keepalive-nas-2.lock bash -c 'dd if=/dev/disk/by-uuid/4617cf0a-493c-40cb-9427-c034d3a5c470 of=/dev/null count=1 skip=$RANDOM > /dev/null 2>&1' > /dev/null"
    user: root
  - name: "Keep backup upnp_1 HDD (WD Elements) alive (spinning)"
    minute: "*/5"
    job: "flock --verbose -n /tmp/keepalive-backup-1.lock bash -c 'dd if=/dev/disk/by-uuid/5d3675f9-f036-4f45-9e12-f1227eee2df4 of=/dev/null count=1 skip=$RANDOM > /dev/null 2>&1' > /dev/null"
    user: root
  - name: "Keep backup upnp_2 HDD (WD Elements) alive (spinning)"
    minute: "*/5"
    job: "flock --verbose -n /tmp/keepalive-backup-2.lock bash -c 'dd if=/dev/disk/by-uuid/8d5fdd3d-f084-4e34-b120-6c2f8d19354e of=/dev/null count=1 skip=$RANDOM > /dev/null 2>&1' > /dev/null"
    user: root
